-- Create custom types
CREATE TYPE public.subscription_plan AS ENUM ('FREE', 'BASIC', 'PREMIUM', 'ENTERPRISE');
CREATE TYPE public.gender_type AS ENUM ('MALE', 'FEMALE', 'UNISEX', 'UNSPECIFIED');

-- Create the helper function for updated_at
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Stores table
CREATE TABLE public.stores (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  store_name character varying(255) NOT NULL,
  store_id character varying(100) NOT NULL,
  password_hash character varying(255) NOT NULL,
  email character varying(255) NULL,
  phone character varying(50) NULL,
  address text NULL,
  created_at timestamp with time zone NULL DEFAULT now(),
  updated_at timestamp with time zone NULL DEFAULT now(),
  subscription_name public.subscription_plan NULL,
  subscription_start_at timestamp with time zone NULL,
  subscription_end_at timestamp with time zone NULL,
  tryons_quota integer NOT NULL DEFAULT 0,
  tryons_used integer NOT NULL DEFAULT 0,
  CONSTRAINT stores_pkey PRIMARY KEY (id),
  CONSTRAINT stores_store_id_key UNIQUE (store_id),
  CONSTRAINT stores_tryons_nonneg CHECK (tryons_quota >= 0 AND tryons_used >= 0),
  CONSTRAINT stores_tryons_used_leq_quota CHECK (tryons_used <= tryons_quota)
);

CREATE INDEX IF NOT EXISTS idx_stores_store_id ON public.stores USING btree (store_id);
CREATE INDEX IF NOT EXISTS idx_stores_subscription_end_at ON public.stores USING btree (subscription_end_at);

CREATE TRIGGER update_stores_updated_at
  BEFORE UPDATE ON stores
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Inventory table
CREATE TABLE public.inventory (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  store_id uuid NOT NULL,
  product_name character varying(255) NOT NULL,
  description text NULL,
  category character varying(100) NULL,
  brand character varying(100) NULL,
  price numeric(10,2) NULL,
  image_url text NULL,
  sizes jsonb NOT NULL DEFAULT '{}'::jsonb,
  measurements jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NULL DEFAULT now(),
  updated_at timestamp with time zone NULL DEFAULT now(),
  product_link text NULL,
  colour character varying NOT NULL DEFAULT 'NULL'::character varying,
  fabric_type character varying(50) NULL DEFAULT 'MEDIUM_STRETCH'::character varying,
  season character varying(50) NULL DEFAULT 'ALL_SEASON'::character varying,
  activity character varying(50) NULL DEFAULT 'CASUAL'::character varying,
  occasion character varying(50) NULL DEFAULT 'WEEKEND_CASUAL'::character varying,
  gender public.gender_type NOT NULL DEFAULT 'UNSPECIFIED'::gender_type,
  "3d_front_image" text NULL,
  "3d_back_image" text NULL,
  CONSTRAINT inventory_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_store_id_fkey FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_inventory_gender ON public.inventory USING btree (gender);
CREATE INDEX IF NOT EXISTS idx_inventory_store_id ON public.inventory USING btree (store_id);
CREATE INDEX IF NOT EXISTS idx_inventory_product_link ON public.inventory USING btree (product_link) WHERE (product_link IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_inventory_fabric_type ON public.inventory USING btree (fabric_type);
CREATE INDEX IF NOT EXISTS idx_inventory_season ON public.inventory USING btree (season);
CREATE INDEX IF NOT EXISTS idx_inventory_activity ON public.inventory USING btree (activity);
CREATE INDEX IF NOT EXISTS idx_inventory_occasion ON public.inventory USING btree (occasion);

CREATE TRIGGER update_inventory_updated_at
  BEFORE UPDATE ON inventory
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Size Templates table
CREATE TABLE public.size_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  store_id uuid NOT NULL,
  template_name character varying(255) NOT NULL,
  category character varying(100) NULL,
  size_name character varying(50) NOT NULL,
  measurements jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NULL DEFAULT now(),
  updated_at timestamp with time zone NULL DEFAULT now(),
  CONSTRAINT size_templates_pkey PRIMARY KEY (id),
  CONSTRAINT size_templates_store_id_fkey FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_size_templates_store_id ON public.size_templates USING btree (store_id);

CREATE TRIGGER update_size_templates_updated_at
  BEFORE UPDATE ON size_templates
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Users table (minimal for foreign key)
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NULL,
  created_at timestamp with time zone NULL DEFAULT now(),
  PRIMARY KEY (id)
);

-- Conversions table
CREATE TABLE public.conversions (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  user_id uuid NOT NULL,
  store_id text NULL,
  product_id text NULL,
  add_to_cart boolean NULL DEFAULT true,
  status text NULL DEFAULT 'Logged In'::text,
  CONSTRAINT conversions_pkey PRIMARY KEY (id)
);

-- Tryon Analytics table
CREATE TABLE public.tryon_analytics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  store_id uuid NOT NULL,
  product_id uuid NULL,
  user_id uuid NULL,
  tryon_type character varying(50) NOT NULL,
  created_at timestamp with time zone NULL DEFAULT now(),
  redirect_status boolean NOT NULL DEFAULT false,
  CONSTRAINT tryon_analytics_pkey PRIMARY KEY (id),
  CONSTRAINT tryon_analytics_product_id_fkey FOREIGN KEY (product_id) REFERENCES inventory(id) ON DELETE SET NULL,
  CONSTRAINT tryon_analytics_store_id_fkey FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE,
  CONSTRAINT tryon_analytics_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_tryon_analytics_store_id ON public.tryon_analytics USING btree (store_id);
CREATE INDEX IF NOT EXISTS idx_tryon_analytics_created_at ON public.tryon_analytics USING btree (created_at);
CREATE INDEX IF NOT EXISTS idx_tryon_analytics_redirect_status ON public.tryon_analytics USING btree (redirect_status);
CREATE INDEX IF NOT EXISTS idx_tryon_analytics_store_redirect ON public.tryon_analytics USING btree (store_id, redirect_status, created_at);
